version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/qwisedev/ai-code-review:latest
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
    env_file:
      - ./conf/.env
    restart: unless-stopped